[[IgnoredVulns]]
id = "GHSA-vjj6-5m9f-wqjw"

[[IgnoredVulns]]
id = "GHSA-v9w2-543f-h69m"

[[IgnoredVulns]]
id = "GHSA-j96p-r523-8r3w"

[[IgnoredVulns]]
id = "GHSA-9w7j-q3xw-p9vh"

[[IgnoredVulns]]
id = "GO-2024-3099"

[[IgnoredVulns]]
id = "GHSA-48gg-32q2-4r6m"

[[IgnoredVulns]]
id = "GHSA-72x4-cq6r-jp4p"
