// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/anoideaopen/channel-transfer/test/integration/clienthttp/models"
)

// TransferByCustomerReader is a Reader for the TransferByCustomer structure.
type TransferByCustomerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TransferByCustomerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTransferByCustomerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewTransferByCustomerInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewTransferByCustomerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewTransferByCustomerOK creates a TransferByCustomerOK with default headers values
func NewTransferByCustomerOK() *TransferByCustomerOK {
	return &TransferByCustomerOK{}
}

// TransferByCustomerOK handles this case with default header values.
// A successful response.
type TransferByCustomerOK struct {
	Payload *models.ChannelTransferTransferStatusResponse
}

func (o *TransferByCustomerOK) Error() string {
	return fmt.Sprintf("[POST /v1/transfer/customer][%d] transferByCustomerOK  %+v", 200, o.Payload)
}

func (o *TransferByCustomerOK) GetPayload() *models.ChannelTransferTransferStatusResponse {
	return o.Payload
}

func (o *TransferByCustomerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelTransferTransferStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTransferByCustomerInternalServerError creates a TransferByCustomerInternalServerError with default headers values
func NewTransferByCustomerInternalServerError() *TransferByCustomerInternalServerError {
	return &TransferByCustomerInternalServerError{}
}

// TransferByCustomerInternalServerError handles this case with default header values.
// Internal server error
type TransferByCustomerInternalServerError struct {
	Payload *models.ChannelTransferErrorResponse
}

func (o *TransferByCustomerInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/transfer/customer][%d] transferByCustomerInternalServerError  %+v", 500, o.Payload)
}

func (o *TransferByCustomerInternalServerError) GetPayload() *models.ChannelTransferErrorResponse {
	return o.Payload
}

func (o *TransferByCustomerInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelTransferErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTransferByCustomerDefault creates a TransferByCustomerDefault with default headers values
func NewTransferByCustomerDefault(code int) *TransferByCustomerDefault {
	return &TransferByCustomerDefault{
		_statusCode: code,
	}
}

// TransferByCustomerDefault handles this case with default header values.
// An unexpected error response.
type TransferByCustomerDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the transfer by customer default response
func (o *TransferByCustomerDefault) Code() int {
	return o._statusCode
}

func (o *TransferByCustomerDefault) Error() string {
	return fmt.Sprintf("[POST /v1/transfer/customer][%d] transferByCustomer default  %+v", o._statusCode, o.Payload)
}

func (o *TransferByCustomerDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *TransferByCustomerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
*/
