// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/anoideaopen/channel-transfer/test/integration/clienthttp/models"
)

// NewTransferByCustomerParams creates a new TransferByCustomerParams object
// with the default values initialized.
func NewTransferByCustomerParams() *TransferByCustomerParams {
	var ()
	return &TransferByCustomerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTransferByCustomerParamsWithTimeout creates a new TransferByCustomerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTransferByCustomerParamsWithTimeout(timeout time.Duration) *TransferByCustomerParams {
	var ()
	return &TransferByCustomerParams{

		timeout: timeout,
	}
}

// NewTransferByCustomerParamsWithContext creates a new TransferByCustomerParams object
// with the default values initialized, and the ability to set a context for a request
func NewTransferByCustomerParamsWithContext(ctx context.Context) *TransferByCustomerParams {
	var ()
	return &TransferByCustomerParams{

		Context: ctx,
	}
}

// NewTransferByCustomerParamsWithHTTPClient creates a new TransferByCustomerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTransferByCustomerParamsWithHTTPClient(client *http.Client) *TransferByCustomerParams {
	var ()
	return &TransferByCustomerParams{
		HTTPClient: client,
	}
}

/*
TransferByCustomerParams contains all the parameters to send to the API endpoint
for the transfer by customer operation typically these are written to a http.Request
*/
type TransferByCustomerParams struct {

	/*Body*/
	Body *models.ChannelTransferTransferBeginCustomerRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the transfer by customer params
func (o *TransferByCustomerParams) WithTimeout(timeout time.Duration) *TransferByCustomerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the transfer by customer params
func (o *TransferByCustomerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the transfer by customer params
func (o *TransferByCustomerParams) WithContext(ctx context.Context) *TransferByCustomerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the transfer by customer params
func (o *TransferByCustomerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the transfer by customer params
func (o *TransferByCustomerParams) WithHTTPClient(client *http.Client) *TransferByCustomerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the transfer by customer params
func (o *TransferByCustomerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the transfer by customer params
func (o *TransferByCustomerParams) WithBody(body *models.ChannelTransferTransferBeginCustomerRequest) *TransferByCustomerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the transfer by customer params
func (o *TransferByCustomerParams) SetBody(body *models.ChannelTransferTransferBeginCustomerRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TransferByCustomerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
