// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/anoideaopen/channel-transfer/test/integration/models"
)

// TransferStatusReader is a Reader for the TransferStatus structure.
type TransferStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TransferStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTransferStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewTransferStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewTransferStatusDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewTransferStatusOK creates a TransferStatusOK with default headers values
func NewTransferStatusOK() *TransferStatusOK {
	return &TransferStatusOK{}
}

// TransferStatusOK handles this case with default header values.
// A successful response.
type TransferStatusOK struct {
	Payload *models.ChannelTransferTransferStatusResponse
}

func (o *TransferStatusOK) Error() string {
	return fmt.Sprintf("[GET /v1/status/{idTransfer}][%d] transferStatusOK  %+v", 200, o.Payload)
}

func (o *TransferStatusOK) GetPayload() *models.ChannelTransferTransferStatusResponse {
	return o.Payload
}

func (o *TransferStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelTransferTransferStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTransferStatusInternalServerError creates a TransferStatusInternalServerError with default headers values
func NewTransferStatusInternalServerError() *TransferStatusInternalServerError {
	return &TransferStatusInternalServerError{}
}

// TransferStatusInternalServerError handles this case with default header values.
// Internal server error
type TransferStatusInternalServerError struct {
	Payload *models.ChannelTransferErrorResponse
}

func (o *TransferStatusInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/status/{idTransfer}][%d] transferStatusInternalServerError  %+v", 500, o.Payload)
}

func (o *TransferStatusInternalServerError) GetPayload() *models.ChannelTransferErrorResponse {
	return o.Payload
}

func (o *TransferStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelTransferErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTransferStatusDefault creates a TransferStatusDefault with default headers values
func NewTransferStatusDefault(code int) *TransferStatusDefault {
	return &TransferStatusDefault{
		_statusCode: code,
	}
}

// TransferStatusDefault handles this case with default header values.
// An unexpected error response.
type TransferStatusDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the transfer status default response
func (o *TransferStatusDefault) Code() int {
	return o._statusCode
}

func (o *TransferStatusDefault) Error() string {
	return fmt.Sprintf("[GET /v1/status/{idTransfer}][%d] transferStatus default  %+v", o._statusCode, o.Payload)
}

func (o *TransferStatusDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *TransferStatusDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
*/
