// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChannelTransferErrorResponse ErrorResponse response with an error
//
// swagger:model channel_transferErrorResponse
type ChannelTransferErrorResponse struct {

	// error message
	Error string `json:"error,omitempty"`
}

// Validate validates this channel transfer error response
func (m *ChannelTransferErrorResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChannelTransferErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChannelTransferErrorResponse) UnmarshalBinary(b []byte) error {
	var res ChannelTransferErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
