// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChannelTransferTransferStatusResponse TransferStatusResponse response for TransferStatus transaction
//
// swagger:model channel_transferTransferStatusResponse
type ChannelTransferTransferStatusResponse struct {

	// transfer ID
	IDTransfer string `json:"idTransfer,omitempty"`

	// error message (may be empty)
	Message string `json:"message,omitempty"`

	// transfer status
	Status ChannelTransferTransferStatusResponseStatus `json:"status,omitempty"`
}

// Validate validates this channel transfer transfer status response
func (m *ChannelTransferTransferStatusResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChannelTransferTransferStatusResponse) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if err := m.Status.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("status")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ChannelTransferTransferStatusResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChannelTransferTransferStatusResponse) UnmarshalBinary(b []byte) error {
	var res ChannelTransferTransferStatusResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
