// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChannelTransferTransferItem TransferItem item parameters for MultiTransferBeginCustomerRequest and MultiTransferBeginAdminRequest
//
// swagger:model channel_transferTransferItem
type ChannelTransferTransferItem struct {

	// Amount of token to transfer
	Amount string `json:"amount,omitempty"`

	// token's hold
	Hold bool `json:"hold,omitempty"`

	// Token to transfer
	Token string `json:"token,omitempty"`

	// token's owner user
	User string `json:"user,omitempty"`
}

// Validate validates this channel transfer transfer item
func (m *ChannelTransferTransferItem) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChannelTransferTransferItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChannelTransferTransferItem) UnmarshalBinary(b []byte) error {
	var res ChannelTransferTransferItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
