// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: batcher.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HLFBatcherAdapter_SubmitTransaction_FullMethodName = "/core.hlf_batcher.HLFBatcherAdapter/SubmitTransaction"
)

// HLFBatcherAdapterClient is the client API for HLFBatcherAdapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC service for interaction between Channel Transfer and HLF Batcher
type HLFBatcherAdapterClient interface {
	SubmitTransaction(ctx context.Context, in *HlfBatcherRequest, opts ...grpc.CallOption) (*HLFBatcherResponse, error)
}

type hLFBatcherAdapterClient struct {
	cc grpc.ClientConnInterface
}

func NewHLFBatcherAdapterClient(cc grpc.ClientConnInterface) HLFBatcherAdapterClient {
	return &hLFBatcherAdapterClient{cc}
}

func (c *hLFBatcherAdapterClient) SubmitTransaction(ctx context.Context, in *HlfBatcherRequest, opts ...grpc.CallOption) (*HLFBatcherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HLFBatcherResponse)
	err := c.cc.Invoke(ctx, HLFBatcherAdapter_SubmitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HLFBatcherAdapterServer is the server API for HLFBatcherAdapter service.
// All implementations must embed UnimplementedHLFBatcherAdapterServer
// for forward compatibility.
//
// gRPC service for interaction between Channel Transfer and HLF Batcher
type HLFBatcherAdapterServer interface {
	SubmitTransaction(context.Context, *HlfBatcherRequest) (*HLFBatcherResponse, error)
	mustEmbedUnimplementedHLFBatcherAdapterServer()
}

// UnimplementedHLFBatcherAdapterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHLFBatcherAdapterServer struct{}

func (UnimplementedHLFBatcherAdapterServer) SubmitTransaction(context.Context, *HlfBatcherRequest) (*HLFBatcherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedHLFBatcherAdapterServer) mustEmbedUnimplementedHLFBatcherAdapterServer() {}
func (UnimplementedHLFBatcherAdapterServer) testEmbeddedByValue()                           {}

// UnsafeHLFBatcherAdapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HLFBatcherAdapterServer will
// result in compilation errors.
type UnsafeHLFBatcherAdapterServer interface {
	mustEmbedUnimplementedHLFBatcherAdapterServer()
}

func RegisterHLFBatcherAdapterServer(s grpc.ServiceRegistrar, srv HLFBatcherAdapterServer) {
	// If the following call pancis, it indicates UnimplementedHLFBatcherAdapterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HLFBatcherAdapter_ServiceDesc, srv)
}

func _HLFBatcherAdapter_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HlfBatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HLFBatcherAdapterServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HLFBatcherAdapter_SubmitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HLFBatcherAdapterServer).SubmitTransaction(ctx, req.(*HlfBatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HLFBatcherAdapter_ServiceDesc is the grpc.ServiceDesc for HLFBatcherAdapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HLFBatcherAdapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.hlf_batcher.HLFBatcherAdapter",
	HandlerType: (*HLFBatcherAdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTransaction",
			Handler:    _HLFBatcherAdapter_SubmitTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "batcher.proto",
}
