// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	API_TransferByCustomer_FullMethodName      = "/core.channel_transfer.API/TransferByCustomer"
	API_TransferByAdmin_FullMethodName         = "/core.channel_transfer.API/TransferByAdmin"
	API_MultiTransferByCustomer_FullMethodName = "/core.channel_transfer.API/MultiTransferByCustomer"
	API_MultiTransferByAdmin_FullMethodName    = "/core.channel_transfer.API/MultiTransferByAdmin"
	API_TransferStatus_FullMethodName          = "/core.channel_transfer.API/TransferStatus"
)

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIClient interface {
	TransferByCustomer(ctx context.Context, in *TransferBeginCustomerRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error)
	TransferByAdmin(ctx context.Context, in *TransferBeginAdminRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error)
	MultiTransferByCustomer(ctx context.Context, in *MultiTransferBeginCustomerRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error)
	MultiTransferByAdmin(ctx context.Context, in *MultiTransferBeginAdminRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error)
	TransferStatus(ctx context.Context, in *TransferStatusRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) TransferByCustomer(ctx context.Context, in *TransferBeginCustomerRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferStatusResponse)
	err := c.cc.Invoke(ctx, API_TransferByCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) TransferByAdmin(ctx context.Context, in *TransferBeginAdminRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferStatusResponse)
	err := c.cc.Invoke(ctx, API_TransferByAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) MultiTransferByCustomer(ctx context.Context, in *MultiTransferBeginCustomerRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferStatusResponse)
	err := c.cc.Invoke(ctx, API_MultiTransferByCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) MultiTransferByAdmin(ctx context.Context, in *MultiTransferBeginAdminRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferStatusResponse)
	err := c.cc.Invoke(ctx, API_MultiTransferByAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) TransferStatus(ctx context.Context, in *TransferStatusRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferStatusResponse)
	err := c.cc.Invoke(ctx, API_TransferStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
// All implementations must embed UnimplementedAPIServer
// for forward compatibility.
type APIServer interface {
	TransferByCustomer(context.Context, *TransferBeginCustomerRequest) (*TransferStatusResponse, error)
	TransferByAdmin(context.Context, *TransferBeginAdminRequest) (*TransferStatusResponse, error)
	MultiTransferByCustomer(context.Context, *MultiTransferBeginCustomerRequest) (*TransferStatusResponse, error)
	MultiTransferByAdmin(context.Context, *MultiTransferBeginAdminRequest) (*TransferStatusResponse, error)
	TransferStatus(context.Context, *TransferStatusRequest) (*TransferStatusResponse, error)
	mustEmbedUnimplementedAPIServer()
}

// UnimplementedAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAPIServer struct{}

func (UnimplementedAPIServer) TransferByCustomer(context.Context, *TransferBeginCustomerRequest) (*TransferStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferByCustomer not implemented")
}
func (UnimplementedAPIServer) TransferByAdmin(context.Context, *TransferBeginAdminRequest) (*TransferStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferByAdmin not implemented")
}
func (UnimplementedAPIServer) MultiTransferByCustomer(context.Context, *MultiTransferBeginCustomerRequest) (*TransferStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiTransferByCustomer not implemented")
}
func (UnimplementedAPIServer) MultiTransferByAdmin(context.Context, *MultiTransferBeginAdminRequest) (*TransferStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiTransferByAdmin not implemented")
}
func (UnimplementedAPIServer) TransferStatus(context.Context, *TransferStatusRequest) (*TransferStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferStatus not implemented")
}
func (UnimplementedAPIServer) mustEmbedUnimplementedAPIServer() {}
func (UnimplementedAPIServer) testEmbeddedByValue()             {}

// UnsafeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServer will
// result in compilation errors.
type UnsafeAPIServer interface {
	mustEmbedUnimplementedAPIServer()
}

func RegisterAPIServer(s grpc.ServiceRegistrar, srv APIServer) {
	// If the following call pancis, it indicates UnimplementedAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&API_ServiceDesc, srv)
}

func _API_TransferByCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferBeginCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).TransferByCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_TransferByCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).TransferByCustomer(ctx, req.(*TransferBeginCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_TransferByAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferBeginAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).TransferByAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_TransferByAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).TransferByAdmin(ctx, req.(*TransferBeginAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_MultiTransferByCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiTransferBeginCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).MultiTransferByCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_MultiTransferByCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).MultiTransferByCustomer(ctx, req.(*MultiTransferBeginCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_MultiTransferByAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiTransferBeginAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).MultiTransferByAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_MultiTransferByAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).MultiTransferByAdmin(ctx, req.(*MultiTransferBeginAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_TransferStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).TransferStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_TransferStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).TransferStatus(ctx, req.(*TransferStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// API_ServiceDesc is the grpc.ServiceDesc for API service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var API_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.channel_transfer.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferByCustomer",
			Handler:    _API_TransferByCustomer_Handler,
		},
		{
			MethodName: "TransferByAdmin",
			Handler:    _API_TransferByAdmin_Handler,
		},
		{
			MethodName: "MultiTransferByCustomer",
			Handler:    _API_MultiTransferByCustomer_Handler,
		},
		{
			MethodName: "MultiTransferByAdmin",
			Handler:    _API_MultiTransferByAdmin_Handler,
		},
		{
			MethodName: "TransferStatus",
			Handler:    _API_TransferStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
