// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: service.proto

package proto

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	typepb "google.golang.org/protobuf/types/known/typepb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferStatusResponse_Status int32

const (
	TransferStatusResponse_STATUS_IN_PROCESS TransferStatusResponse_Status = 0
	TransferStatusResponse_STATUS_UNDEFINED  TransferStatusResponse_Status = 1
	TransferStatusResponse_STATUS_COMPLETED  TransferStatusResponse_Status = 2
	TransferStatusResponse_STATUS_CANCELED   TransferStatusResponse_Status = 3
	TransferStatusResponse_STATUS_ERROR      TransferStatusResponse_Status = 4
)

// Enum value maps for TransferStatusResponse_Status.
var (
	TransferStatusResponse_Status_name = map[int32]string{
		0: "STATUS_IN_PROCESS",
		1: "STATUS_UNDEFINED",
		2: "STATUS_COMPLETED",
		3: "STATUS_CANCELED",
		4: "STATUS_ERROR",
	}
	TransferStatusResponse_Status_value = map[string]int32{
		"STATUS_IN_PROCESS": 0,
		"STATUS_UNDEFINED":  1,
		"STATUS_COMPLETED":  2,
		"STATUS_CANCELED":   3,
		"STATUS_ERROR":      4,
	}
)

func (x TransferStatusResponse_Status) Enum() *TransferStatusResponse_Status {
	p := new(TransferStatusResponse_Status)
	*p = x
	return p
}

func (x TransferStatusResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferStatusResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (TransferStatusResponse_Status) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x TransferStatusResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferStatusResponse_Status.Descriptor instead.
func (TransferStatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7, 0}
}

// ErrorResponse response with an error
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GeneralParams general parameters for every request
type GeneralParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MethodName    string                 `protobuf:"bytes,1,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"` // method name
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`    // request ID (may be empty)
	Chaincode     string                 `protobuf:"bytes,3,opt,name=chaincode,proto3" json:"chaincode,omitempty"`                     // chaincode name
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`                         // channel name
	Nonce         string                 `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`                             // request nonce
	PublicKey     string                 `protobuf:"bytes,6,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`    // public key of user, signed the request
	Sign          string                 `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`                               // request sign
	Options       []*typepb.Option       `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralParams) Reset() {
	*x = GeneralParams{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralParams) ProtoMessage() {}

func (x *GeneralParams) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralParams.ProtoReflect.Descriptor instead.
func (*GeneralParams) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *GeneralParams) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *GeneralParams) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GeneralParams) GetChaincode() string {
	if x != nil {
		return x.Chaincode
	}
	return ""
}

func (x *GeneralParams) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *GeneralParams) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *GeneralParams) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *GeneralParams) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *GeneralParams) GetOptions() []*typepb.Option {
	if x != nil {
		return x.Options
	}
	return nil
}

// TransferBeginCustomerRequest request for tokens transfer by tokens owner
type TransferBeginCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generals      *GeneralParams         `protobuf:"bytes,1,opt,name=generals,proto3" json:"generals,omitempty"`                       // general parameters
	IdTransfer    string                 `protobuf:"bytes,2,opt,name=id_transfer,json=idTransfer,proto3" json:"id_transfer,omitempty"` // transfer ID (should be unique)
	ChannelTo     string                 `protobuf:"bytes,3,opt,name=channel_to,json=channelTo,proto3" json:"channel_to,omitempty"`    // destination channel
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                             // Tokens to transfer
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`                           // Amount of tokens to transfer
	Options       []*typepb.Option       `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferBeginCustomerRequest) Reset() {
	*x = TransferBeginCustomerRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferBeginCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferBeginCustomerRequest) ProtoMessage() {}

func (x *TransferBeginCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferBeginCustomerRequest.ProtoReflect.Descriptor instead.
func (*TransferBeginCustomerRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *TransferBeginCustomerRequest) GetGenerals() *GeneralParams {
	if x != nil {
		return x.Generals
	}
	return nil
}

func (x *TransferBeginCustomerRequest) GetIdTransfer() string {
	if x != nil {
		return x.IdTransfer
	}
	return ""
}

func (x *TransferBeginCustomerRequest) GetChannelTo() string {
	if x != nil {
		return x.ChannelTo
	}
	return ""
}

func (x *TransferBeginCustomerRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TransferBeginCustomerRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransferBeginCustomerRequest) GetOptions() []*typepb.Option {
	if x != nil {
		return x.Options
	}
	return nil
}

// TransferBeginAdminRequest request for tokens transfer by platform administrator
type TransferBeginAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generals      *GeneralParams         `protobuf:"bytes,1,opt,name=generals,proto3" json:"generals,omitempty"`                       // general parameters
	IdTransfer    string                 `protobuf:"bytes,2,opt,name=id_transfer,json=idTransfer,proto3" json:"id_transfer,omitempty"` // transfer ID (should be unique)
	ChannelTo     string                 `protobuf:"bytes,3,opt,name=channel_to,json=channelTo,proto3" json:"channel_to,omitempty"`    // destination channel
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`                         // token's owner address
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`                             // tokens to transfer
	Amount        string                 `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`                           // amount of tokens to transfer
	Options       []*typepb.Option       `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferBeginAdminRequest) Reset() {
	*x = TransferBeginAdminRequest{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferBeginAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferBeginAdminRequest) ProtoMessage() {}

func (x *TransferBeginAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferBeginAdminRequest.ProtoReflect.Descriptor instead.
func (*TransferBeginAdminRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *TransferBeginAdminRequest) GetGenerals() *GeneralParams {
	if x != nil {
		return x.Generals
	}
	return nil
}

func (x *TransferBeginAdminRequest) GetIdTransfer() string {
	if x != nil {
		return x.IdTransfer
	}
	return ""
}

func (x *TransferBeginAdminRequest) GetChannelTo() string {
	if x != nil {
		return x.ChannelTo
	}
	return ""
}

func (x *TransferBeginAdminRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TransferBeginAdminRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TransferBeginAdminRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransferBeginAdminRequest) GetOptions() []*typepb.Option {
	if x != nil {
		return x.Options
	}
	return nil
}

// TransferItem item parameters for MultiTransferBeginCustomerRequest and MultiTransferBeginAdminRequest
type TransferItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`   // Token to transfer
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"` // Amount of token to transfer
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`     // token's owner user
	Hold          bool                   `protobuf:"varint,4,opt,name=hold,proto3" json:"hold,omitempty"`    // token's hold
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferItem) Reset() {
	*x = TransferItem{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferItem) ProtoMessage() {}

func (x *TransferItem) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferItem.ProtoReflect.Descriptor instead.
func (*TransferItem) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *TransferItem) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TransferItem) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransferItem) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *TransferItem) GetHold() bool {
	if x != nil {
		return x.Hold
	}
	return false
}

// MultiTransferBeginAdminRequest request for tokens transfer by tokens owner
type MultiTransferBeginCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generals      *GeneralParams         `protobuf:"bytes,1,opt,name=generals,proto3" json:"generals,omitempty"`                       // general parameters
	IdTransfer    string                 `protobuf:"bytes,2,opt,name=id_transfer,json=idTransfer,proto3" json:"id_transfer,omitempty"` // transfer ID (should be unique)
	ChannelTo     string                 `protobuf:"bytes,3,opt,name=channel_to,json=channelTo,proto3" json:"channel_to,omitempty"`    // destination channel
	Items         []*TransferItem        `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`                             // items to transfer
	Options       []*typepb.Option       `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiTransferBeginCustomerRequest) Reset() {
	*x = MultiTransferBeginCustomerRequest{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiTransferBeginCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTransferBeginCustomerRequest) ProtoMessage() {}

func (x *MultiTransferBeginCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiTransferBeginCustomerRequest.ProtoReflect.Descriptor instead.
func (*MultiTransferBeginCustomerRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *MultiTransferBeginCustomerRequest) GetGenerals() *GeneralParams {
	if x != nil {
		return x.Generals
	}
	return nil
}

func (x *MultiTransferBeginCustomerRequest) GetIdTransfer() string {
	if x != nil {
		return x.IdTransfer
	}
	return ""
}

func (x *MultiTransferBeginCustomerRequest) GetChannelTo() string {
	if x != nil {
		return x.ChannelTo
	}
	return ""
}

func (x *MultiTransferBeginCustomerRequest) GetItems() []*TransferItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *MultiTransferBeginCustomerRequest) GetOptions() []*typepb.Option {
	if x != nil {
		return x.Options
	}
	return nil
}

// MultiTransferBeginAdminRequest request for tokens transfer by platform administrator
type MultiTransferBeginAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generals      *GeneralParams         `protobuf:"bytes,1,opt,name=generals,proto3" json:"generals,omitempty"`                       // general parameters
	IdTransfer    string                 `protobuf:"bytes,2,opt,name=id_transfer,json=idTransfer,proto3" json:"id_transfer,omitempty"` // transfer ID (should be unique)
	ChannelTo     string                 `protobuf:"bytes,3,opt,name=channel_to,json=channelTo,proto3" json:"channel_to,omitempty"`    // destination channel
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`                         // token's owner address (deprecated)
	Items         []*TransferItem        `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`                             // items to transfer
	Options       []*typepb.Option       `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiTransferBeginAdminRequest) Reset() {
	*x = MultiTransferBeginAdminRequest{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiTransferBeginAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTransferBeginAdminRequest) ProtoMessage() {}

func (x *MultiTransferBeginAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiTransferBeginAdminRequest.ProtoReflect.Descriptor instead.
func (*MultiTransferBeginAdminRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *MultiTransferBeginAdminRequest) GetGenerals() *GeneralParams {
	if x != nil {
		return x.Generals
	}
	return nil
}

func (x *MultiTransferBeginAdminRequest) GetIdTransfer() string {
	if x != nil {
		return x.IdTransfer
	}
	return ""
}

func (x *MultiTransferBeginAdminRequest) GetChannelTo() string {
	if x != nil {
		return x.ChannelTo
	}
	return ""
}

func (x *MultiTransferBeginAdminRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MultiTransferBeginAdminRequest) GetItems() []*TransferItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *MultiTransferBeginAdminRequest) GetOptions() []*typepb.Option {
	if x != nil {
		return x.Options
	}
	return nil
}

// TransferStatusResponse response for TransferStatus transaction
type TransferStatusResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	IdTransfer    string                        `protobuf:"bytes,1,opt,name=id_transfer,json=idTransfer,proto3" json:"id_transfer,omitempty"`                                 // transfer ID
	Status        TransferStatusResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=core.channel_transfer.TransferStatusResponse_Status" json:"status,omitempty"` // transfer status
	Message       string                        `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                                         // error message (may be empty)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferStatusResponse) Reset() {
	*x = TransferStatusResponse{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStatusResponse) ProtoMessage() {}

func (x *TransferStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStatusResponse.ProtoReflect.Descriptor instead.
func (*TransferStatusResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *TransferStatusResponse) GetIdTransfer() string {
	if x != nil {
		return x.IdTransfer
	}
	return ""
}

func (x *TransferStatusResponse) GetStatus() TransferStatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return TransferStatusResponse_STATUS_IN_PROCESS
}

func (x *TransferStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TransferStatusRequest request for transfer status
type TransferStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdTransfer    string                 `protobuf:"bytes,1,opt,name=id_transfer,json=idTransfer,proto3" json:"id_transfer,omitempty"` // transfer ID
	Options       []*typepb.Option       `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferStatusRequest) Reset() {
	*x = TransferStatusRequest{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStatusRequest) ProtoMessage() {}

func (x *TransferStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStatusRequest.ProtoReflect.Descriptor instead.
func (*TransferStatusRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *TransferStatusRequest) GetIdTransfer() string {
	if x != nil {
		return x.IdTransfer
	}
	return ""
}

func (x *TransferStatusRequest) GetOptions() []*typepb.Option {
	if x != nil {
		return x.Options
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x15core.channel_transfer\x1a\x1cgoogle/api/annotations.proto\x1a\x1agoogle/protobuf/type.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"%\n" +
	"\rErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x83\x02\n" +
	"\rGeneralParams\x12\x1f\n" +
	"\vmethod_name\x18\x01 \x01(\tR\n" +
	"methodName\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1c\n" +
	"\tchaincode\x18\x03 \x01(\tR\tchaincode\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\tR\x05nonce\x12\x1d\n" +
	"\n" +
	"public_key\x18\x06 \x01(\tR\tpublicKey\x12\x12\n" +
	"\x04sign\x18\a \x01(\tR\x04sign\x121\n" +
	"\aoptions\x18\b \x03(\v2\x17.google.protobuf.OptionR\aoptions\"\x81\x02\n" +
	"\x1cTransferBeginCustomerRequest\x12@\n" +
	"\bgenerals\x18\x01 \x01(\v2$.core.channel_transfer.GeneralParamsR\bgenerals\x12\x1f\n" +
	"\vid_transfer\x18\x02 \x01(\tR\n" +
	"idTransfer\x12\x1d\n" +
	"\n" +
	"channel_to\x18\x03 \x01(\tR\tchannelTo\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x121\n" +
	"\aoptions\x18\x06 \x03(\v2\x17.google.protobuf.OptionR\aoptions\"\x98\x02\n" +
	"\x19TransferBeginAdminRequest\x12@\n" +
	"\bgenerals\x18\x01 \x01(\v2$.core.channel_transfer.GeneralParamsR\bgenerals\x12\x1f\n" +
	"\vid_transfer\x18\x02 \x01(\tR\n" +
	"idTransfer\x12\x1d\n" +
	"\n" +
	"channel_to\x18\x03 \x01(\tR\tchannelTo\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\tR\x06amount\x121\n" +
	"\aoptions\x18\a \x03(\v2\x17.google.protobuf.OptionR\aoptions\"d\n" +
	"\fTransferItem\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x12\n" +
	"\x04hold\x18\x04 \x01(\bR\x04hold\"\x93\x02\n" +
	"!MultiTransferBeginCustomerRequest\x12@\n" +
	"\bgenerals\x18\x01 \x01(\v2$.core.channel_transfer.GeneralParamsR\bgenerals\x12\x1f\n" +
	"\vid_transfer\x18\x02 \x01(\tR\n" +
	"idTransfer\x12\x1d\n" +
	"\n" +
	"channel_to\x18\x03 \x01(\tR\tchannelTo\x129\n" +
	"\x05items\x18\x04 \x03(\v2#.core.channel_transfer.TransferItemR\x05items\x121\n" +
	"\aoptions\x18\x05 \x03(\v2\x17.google.protobuf.OptionR\aoptions\"\xaa\x02\n" +
	"\x1eMultiTransferBeginAdminRequest\x12@\n" +
	"\bgenerals\x18\x01 \x01(\v2$.core.channel_transfer.GeneralParamsR\bgenerals\x12\x1f\n" +
	"\vid_transfer\x18\x02 \x01(\tR\n" +
	"idTransfer\x12\x1d\n" +
	"\n" +
	"channel_to\x18\x03 \x01(\tR\tchannelTo\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x129\n" +
	"\x05items\x18\x05 \x03(\v2#.core.channel_transfer.TransferItemR\x05items\x121\n" +
	"\aoptions\x18\x06 \x03(\v2\x17.google.protobuf.OptionR\aoptions\"\x95\x02\n" +
	"\x16TransferStatusResponse\x12\x1f\n" +
	"\vid_transfer\x18\x01 \x01(\tR\n" +
	"idTransfer\x12L\n" +
	"\x06status\x18\x02 \x01(\x0e24.core.channel_transfer.TransferStatusResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"r\n" +
	"\x06Status\x12\x15\n" +
	"\x11STATUS_IN_PROCESS\x10\x00\x12\x14\n" +
	"\x10STATUS_UNDEFINED\x10\x01\x12\x14\n" +
	"\x10STATUS_COMPLETED\x10\x02\x12\x13\n" +
	"\x0fSTATUS_CANCELED\x10\x03\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x04\"k\n" +
	"\x15TransferStatusRequest\x12\x1f\n" +
	"\vid_transfer\x18\x01 \x01(\tR\n" +
	"idTransfer\x121\n" +
	"\aoptions\x18\x02 \x03(\v2\x17.google.protobuf.OptionR\aoptions2\xf8\b\n" +
	"\x03API\x12\xdf\x01\n" +
	"\x12TransferByCustomer\x123.core.channel_transfer.TransferBeginCustomerRequest\x1a-.core.channel_transfer.TransferStatusResponse\"e\x92AB\n" +
	"\bTransfer\x12\"Transfer cross channel by customer*\x12transferByCustomer\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/transfer/customer\x12\xd0\x01\n" +
	"\x0fTransferByAdmin\x120.core.channel_transfer.TransferBeginAdminRequest\x1a-.core.channel_transfer.TransferStatusResponse\"\\\x92A<\n" +
	"\bTransfer\x12\x1fTransfer cross channel by admin*\x0ftransferByAdmin\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/transfer/admin\x12\xfa\x01\n" +
	"\x17MultiTransferByCustomer\x128.core.channel_transfer.MultiTransferBeginCustomerRequest\x1a-.core.channel_transfer.TransferStatusResponse\"v\x92AM\n" +
	"\bTransfer\x12(Multi transfer cross channel by customer*\x17multiTransferByCustomer\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/multi-transfer/customer\x12\xeb\x01\n" +
	"\x14MultiTransferByAdmin\x125.core.channel_transfer.MultiTransferBeginAdminRequest\x1a-.core.channel_transfer.TransferStatusResponse\"m\x92AG\n" +
	"\bTransfer\x12%Multi transfer cross channel by admin*\x14multiTransferByAdmin\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/multi-transfer/admin\x12\xd0\x01\n" +
	"\x0eTransferStatus\x12,.core.channel_transfer.TransferStatusRequest\x1a-.core.channel_transfer.TransferStatusResponse\"a\x92A>\n" +
	"\bTransfer\x12\"Get status transfer by id transfer*\x0etransferStatus\x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/status/{id_transfer}B\xd0\x01\x92A\x9d\x01\x12*\n" +
	"\x15Cross chanel transfer*\f\n" +
	"\n" +
	"Apache-2.02\x031.0*\x01\x012\x10application/json:\x10application/jsonRH\n" +
	"\x03500\x12A\n" +
	"\x15Internal server error\x12(\n" +
	"&\x1a$.core.channel_transfer.ErrorResponseZ-github.com/anoideaopen/channel-transfer/protob\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_service_proto_goTypes = []any{
	(TransferStatusResponse_Status)(0),        // 0: core.channel_transfer.TransferStatusResponse.Status
	(*ErrorResponse)(nil),                     // 1: core.channel_transfer.ErrorResponse
	(*GeneralParams)(nil),                     // 2: core.channel_transfer.GeneralParams
	(*TransferBeginCustomerRequest)(nil),      // 3: core.channel_transfer.TransferBeginCustomerRequest
	(*TransferBeginAdminRequest)(nil),         // 4: core.channel_transfer.TransferBeginAdminRequest
	(*TransferItem)(nil),                      // 5: core.channel_transfer.TransferItem
	(*MultiTransferBeginCustomerRequest)(nil), // 6: core.channel_transfer.MultiTransferBeginCustomerRequest
	(*MultiTransferBeginAdminRequest)(nil),    // 7: core.channel_transfer.MultiTransferBeginAdminRequest
	(*TransferStatusResponse)(nil),            // 8: core.channel_transfer.TransferStatusResponse
	(*TransferStatusRequest)(nil),             // 9: core.channel_transfer.TransferStatusRequest
	(*typepb.Option)(nil),                     // 10: google.protobuf.Option
}
var file_service_proto_depIdxs = []int32{
	10, // 0: core.channel_transfer.GeneralParams.options:type_name -> google.protobuf.Option
	2,  // 1: core.channel_transfer.TransferBeginCustomerRequest.generals:type_name -> core.channel_transfer.GeneralParams
	10, // 2: core.channel_transfer.TransferBeginCustomerRequest.options:type_name -> google.protobuf.Option
	2,  // 3: core.channel_transfer.TransferBeginAdminRequest.generals:type_name -> core.channel_transfer.GeneralParams
	10, // 4: core.channel_transfer.TransferBeginAdminRequest.options:type_name -> google.protobuf.Option
	2,  // 5: core.channel_transfer.MultiTransferBeginCustomerRequest.generals:type_name -> core.channel_transfer.GeneralParams
	5,  // 6: core.channel_transfer.MultiTransferBeginCustomerRequest.items:type_name -> core.channel_transfer.TransferItem
	10, // 7: core.channel_transfer.MultiTransferBeginCustomerRequest.options:type_name -> google.protobuf.Option
	2,  // 8: core.channel_transfer.MultiTransferBeginAdminRequest.generals:type_name -> core.channel_transfer.GeneralParams
	5,  // 9: core.channel_transfer.MultiTransferBeginAdminRequest.items:type_name -> core.channel_transfer.TransferItem
	10, // 10: core.channel_transfer.MultiTransferBeginAdminRequest.options:type_name -> google.protobuf.Option
	0,  // 11: core.channel_transfer.TransferStatusResponse.status:type_name -> core.channel_transfer.TransferStatusResponse.Status
	10, // 12: core.channel_transfer.TransferStatusRequest.options:type_name -> google.protobuf.Option
	3,  // 13: core.channel_transfer.API.TransferByCustomer:input_type -> core.channel_transfer.TransferBeginCustomerRequest
	4,  // 14: core.channel_transfer.API.TransferByAdmin:input_type -> core.channel_transfer.TransferBeginAdminRequest
	6,  // 15: core.channel_transfer.API.MultiTransferByCustomer:input_type -> core.channel_transfer.MultiTransferBeginCustomerRequest
	7,  // 16: core.channel_transfer.API.MultiTransferByAdmin:input_type -> core.channel_transfer.MultiTransferBeginAdminRequest
	9,  // 17: core.channel_transfer.API.TransferStatus:input_type -> core.channel_transfer.TransferStatusRequest
	8,  // 18: core.channel_transfer.API.TransferByCustomer:output_type -> core.channel_transfer.TransferStatusResponse
	8,  // 19: core.channel_transfer.API.TransferByAdmin:output_type -> core.channel_transfer.TransferStatusResponse
	8,  // 20: core.channel_transfer.API.MultiTransferByCustomer:output_type -> core.channel_transfer.TransferStatusResponse
	8,  // 21: core.channel_transfer.API.MultiTransferByAdmin:output_type -> core.channel_transfer.TransferStatusResponse
	8,  // 22: core.channel_transfer.API.TransferStatus:output_type -> core.channel_transfer.TransferStatusResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
