// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: task_executor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enumeration for response status
type TaskExecutorResponse_Status int32

const (
	TaskExecutorResponse_STATUS_UNKNOWN  TaskExecutorResponse_Status = 0 // Default, unspecified status
	TaskExecutorResponse_STATUS_ACCEPTED TaskExecutorResponse_Status = 1 // Request accepted for processing
	TaskExecutorResponse_STATUS_REJECTED TaskExecutorResponse_Status = 2 // Request rejected
)

// Enum value maps for TaskExecutorResponse_Status.
var (
	TaskExecutorResponse_Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_ACCEPTED",
		2: "STATUS_REJECTED",
	}
	TaskExecutorResponse_Status_value = map[string]int32{
		"STATUS_UNKNOWN":  0,
		"STATUS_ACCEPTED": 1,
		"STATUS_REJECTED": 2,
	}
)

func (x TaskExecutorResponse_Status) Enum() *TaskExecutorResponse_Status {
	p := new(TaskExecutorResponse_Status)
	*p = x
	return p
}

func (x TaskExecutorResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskExecutorResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_task_executor_proto_enumTypes[0].Descriptor()
}

func (TaskExecutorResponse_Status) Type() protoreflect.EnumType {
	return &file_task_executor_proto_enumTypes[0]
}

func (x TaskExecutorResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskExecutorResponse_Status.Descriptor instead.
func (TaskExecutorResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_task_executor_proto_rawDescGZIP(), []int{1, 0}
}

// Simplified request for gRPC Task Executor service
type TaskExecutorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel   string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`     // Channel identifier (mandatory)
	Chaincode string   `protobuf:"bytes,2,opt,name=chaincode,proto3" json:"chaincode,omitempty"` // Chaincode identifier (mandatory)
	Method    string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`       // Method, the chaincode function to invoke (mandatory)
	Args      [][]byte `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`           // Arguments for the chaincode function (mandatory)
}

func (x *TaskExecutorRequest) Reset() {
	*x = TaskExecutorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_executor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskExecutorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecutorRequest) ProtoMessage() {}

func (x *TaskExecutorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_executor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecutorRequest.ProtoReflect.Descriptor instead.
func (*TaskExecutorRequest) Descriptor() ([]byte, []int) {
	return file_task_executor_proto_rawDescGZIP(), []int{0}
}

func (x *TaskExecutorRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *TaskExecutorRequest) GetChaincode() string {
	if x != nil {
		return x.Chaincode
	}
	return ""
}

func (x *TaskExecutorRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TaskExecutorRequest) GetArgs() [][]byte {
	if x != nil {
		return x.Args
	}
	return nil
}

// Response from Task Executor to Channel Transfer
type TaskExecutorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  TaskExecutorResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=core.task_executor.TaskExecutorResponse_Status" json:"status,omitempty"` // Status of the request ("accepted" or "rejected")
	Message string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                    // Confirmation or error message (optional)
}

func (x *TaskExecutorResponse) Reset() {
	*x = TaskExecutorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_executor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskExecutorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecutorResponse) ProtoMessage() {}

func (x *TaskExecutorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_executor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecutorResponse.ProtoReflect.Descriptor instead.
func (*TaskExecutorResponse) Descriptor() ([]byte, []int) {
	return file_task_executor_proto_rawDescGZIP(), []int{1}
}

func (x *TaskExecutorResponse) GetStatus() TaskExecutorResponse_Status {
	if x != nil {
		return x.Status
	}
	return TaskExecutorResponse_STATUS_UNKNOWN
}

func (x *TaskExecutorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_task_executor_proto protoreflect.FileDescriptor

var file_task_executor_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x22, 0x79, 0x0a, 0x13, 0x54, 0x61, 0x73,
	0x6b, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x22, 0xc1, 0x01, 0x0a, 0x14, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2f, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x6f, 0x72, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x46, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x13,
	0x0a, 0x0f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x45,
	0x44, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x45,
	0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x32, 0x7d, 0x0a, 0x13, 0x54, 0x61, 0x73, 0x6b,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12,
	0x66, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x6f, 0x72, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x65, 0x61, 0x6f, 0x70, 0x65,
	0x6e, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_task_executor_proto_rawDescOnce sync.Once
	file_task_executor_proto_rawDescData = file_task_executor_proto_rawDesc
)

func file_task_executor_proto_rawDescGZIP() []byte {
	file_task_executor_proto_rawDescOnce.Do(func() {
		file_task_executor_proto_rawDescData = protoimpl.X.CompressGZIP(file_task_executor_proto_rawDescData)
	})
	return file_task_executor_proto_rawDescData
}

var file_task_executor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_task_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_task_executor_proto_goTypes = []any{
	(TaskExecutorResponse_Status)(0), // 0: core.task_executor.TaskExecutorResponse.Status
	(*TaskExecutorRequest)(nil),      // 1: core.task_executor.TaskExecutorRequest
	(*TaskExecutorResponse)(nil),     // 2: core.task_executor.TaskExecutorResponse
}
var file_task_executor_proto_depIdxs = []int32{
	0, // 0: core.task_executor.TaskExecutorResponse.status:type_name -> core.task_executor.TaskExecutorResponse.Status
	1, // 1: core.task_executor.TaskExecutorAdapter.SubmitTransaction:input_type -> core.task_executor.TaskExecutorRequest
	2, // 2: core.task_executor.TaskExecutorAdapter.SubmitTransaction:output_type -> core.task_executor.TaskExecutorResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_task_executor_proto_init() }
func file_task_executor_proto_init() {
	if File_task_executor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_task_executor_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TaskExecutorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_executor_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TaskExecutorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_task_executor_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_executor_proto_goTypes,
		DependencyIndexes: file_task_executor_proto_depIdxs,
		EnumInfos:         file_task_executor_proto_enumTypes,
		MessageInfos:      file_task_executor_proto_msgTypes,
	}.Build()
	File_task_executor_proto = out.File
	file_task_executor_proto_rawDesc = nil
	file_task_executor_proto_goTypes = nil
	file_task_executor_proto_depIdxs = nil
}
