// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: task_executor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskExecutorAdapter_SubmitTransaction_FullMethodName = "/core.task_executor.TaskExecutorAdapter/SubmitTransaction"
)

// TaskExecutorAdapterClient is the client API for TaskExecutorAdapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC service for interaction between Channel Transfer and HLF Batcher
type TaskExecutorAdapterClient interface {
	SubmitTransaction(ctx context.Context, in *TaskExecutorRequest, opts ...grpc.CallOption) (*TaskExecutorResponse, error)
}

type taskExecutorAdapterClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskExecutorAdapterClient(cc grpc.ClientConnInterface) TaskExecutorAdapterClient {
	return &taskExecutorAdapterClient{cc}
}

func (c *taskExecutorAdapterClient) SubmitTransaction(ctx context.Context, in *TaskExecutorRequest, opts ...grpc.CallOption) (*TaskExecutorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskExecutorResponse)
	err := c.cc.Invoke(ctx, TaskExecutorAdapter_SubmitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskExecutorAdapterServer is the server API for TaskExecutorAdapter service.
// All implementations must embed UnimplementedTaskExecutorAdapterServer
// for forward compatibility.
//
// gRPC service for interaction between Channel Transfer and HLF Batcher
type TaskExecutorAdapterServer interface {
	SubmitTransaction(context.Context, *TaskExecutorRequest) (*TaskExecutorResponse, error)
	mustEmbedUnimplementedTaskExecutorAdapterServer()
}

// UnimplementedTaskExecutorAdapterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskExecutorAdapterServer struct{}

func (UnimplementedTaskExecutorAdapterServer) SubmitTransaction(context.Context, *TaskExecutorRequest) (*TaskExecutorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedTaskExecutorAdapterServer) mustEmbedUnimplementedTaskExecutorAdapterServer() {}
func (UnimplementedTaskExecutorAdapterServer) testEmbeddedByValue()                             {}

// UnsafeTaskExecutorAdapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskExecutorAdapterServer will
// result in compilation errors.
type UnsafeTaskExecutorAdapterServer interface {
	mustEmbedUnimplementedTaskExecutorAdapterServer()
}

func RegisterTaskExecutorAdapterServer(s grpc.ServiceRegistrar, srv TaskExecutorAdapterServer) {
	// If the following call pancis, it indicates UnimplementedTaskExecutorAdapterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskExecutorAdapter_ServiceDesc, srv)
}

func _TaskExecutorAdapter_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskExecutorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskExecutorAdapterServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskExecutorAdapter_SubmitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskExecutorAdapterServer).SubmitTransaction(ctx, req.(*TaskExecutorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskExecutorAdapter_ServiceDesc is the grpc.ServiceDesc for TaskExecutorAdapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskExecutorAdapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.task_executor.TaskExecutorAdapter",
	HandlerType: (*TaskExecutorAdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTransaction",
			Handler:    _TaskExecutorAdapter_SubmitTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task_executor.proto",
}
