// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: task_executor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enumeration for response status
type TaskExecutorResponse_Status int32

const (
	TaskExecutorResponse_STATUS_UNKNOWN  TaskExecutorResponse_Status = 0 // Default, unspecified status
	TaskExecutorResponse_STATUS_ACCEPTED TaskExecutorResponse_Status = 1 // Request accepted for processing
	TaskExecutorResponse_STATUS_REJECTED TaskExecutorResponse_Status = 2 // Request rejected
)

// Enum value maps for TaskExecutorResponse_Status.
var (
	TaskExecutorResponse_Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_ACCEPTED",
		2: "STATUS_REJECTED",
	}
	TaskExecutorResponse_Status_value = map[string]int32{
		"STATUS_UNKNOWN":  0,
		"STATUS_ACCEPTED": 1,
		"STATUS_REJECTED": 2,
	}
)

func (x TaskExecutorResponse_Status) Enum() *TaskExecutorResponse_Status {
	p := new(TaskExecutorResponse_Status)
	*p = x
	return p
}

func (x TaskExecutorResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskExecutorResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_task_executor_proto_enumTypes[0].Descriptor()
}

func (TaskExecutorResponse_Status) Type() protoreflect.EnumType {
	return &file_task_executor_proto_enumTypes[0]
}

func (x TaskExecutorResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskExecutorResponse_Status.Descriptor instead.
func (TaskExecutorResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_task_executor_proto_rawDescGZIP(), []int{1, 0}
}

// Simplified request for gRPC Task Executor service
type TaskExecutorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`     // Channel identifier (mandatory)
	Chaincode     string                 `protobuf:"bytes,2,opt,name=chaincode,proto3" json:"chaincode,omitempty"` // Chaincode identifier (mandatory)
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`       // Method, the chaincode function to invoke (mandatory)
	Args          [][]byte               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`           // Arguments for the chaincode function (mandatory)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecutorRequest) Reset() {
	*x = TaskExecutorRequest{}
	mi := &file_task_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecutorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecutorRequest) ProtoMessage() {}

func (x *TaskExecutorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecutorRequest.ProtoReflect.Descriptor instead.
func (*TaskExecutorRequest) Descriptor() ([]byte, []int) {
	return file_task_executor_proto_rawDescGZIP(), []int{0}
}

func (x *TaskExecutorRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *TaskExecutorRequest) GetChaincode() string {
	if x != nil {
		return x.Chaincode
	}
	return ""
}

func (x *TaskExecutorRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TaskExecutorRequest) GetArgs() [][]byte {
	if x != nil {
		return x.Args
	}
	return nil
}

// Response from Task Executor to Channel Transfer
type TaskExecutorResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        TaskExecutorResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=core.task_executor.TaskExecutorResponse_Status" json:"status,omitempty"` // Status of the request ("accepted" or "rejected")
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                    // Confirmation or error message (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecutorResponse) Reset() {
	*x = TaskExecutorResponse{}
	mi := &file_task_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecutorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecutorResponse) ProtoMessage() {}

func (x *TaskExecutorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecutorResponse.ProtoReflect.Descriptor instead.
func (*TaskExecutorResponse) Descriptor() ([]byte, []int) {
	return file_task_executor_proto_rawDescGZIP(), []int{1}
}

func (x *TaskExecutorResponse) GetStatus() TaskExecutorResponse_Status {
	if x != nil {
		return x.Status
	}
	return TaskExecutorResponse_STATUS_UNKNOWN
}

func (x *TaskExecutorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_task_executor_proto protoreflect.FileDescriptor

const file_task_executor_proto_rawDesc = "" +
	"\n" +
	"\x13task_executor.proto\x12\x12core.task_executor\"y\n" +
	"\x13TaskExecutorRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1c\n" +
	"\tchaincode\x18\x02 \x01(\tR\tchaincode\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04args\x18\x04 \x03(\fR\x04args\"\xc1\x01\n" +
	"\x14TaskExecutorResponse\x12G\n" +
	"\x06status\x18\x01 \x01(\x0e2/.core.task_executor.TaskExecutorResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fSTATUS_ACCEPTED\x10\x01\x12\x13\n" +
	"\x0fSTATUS_REJECTED\x10\x022}\n" +
	"\x13TaskExecutorAdapter\x12f\n" +
	"\x11SubmitTransaction\x12'.core.task_executor.TaskExecutorRequest\x1a(.core.task_executor.TaskExecutorResponseB/Z-github.com/anoideaopen/channel-transfer/protob\x06proto3"

var (
	file_task_executor_proto_rawDescOnce sync.Once
	file_task_executor_proto_rawDescData []byte
)

func file_task_executor_proto_rawDescGZIP() []byte {
	file_task_executor_proto_rawDescOnce.Do(func() {
		file_task_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_executor_proto_rawDesc), len(file_task_executor_proto_rawDesc)))
	})
	return file_task_executor_proto_rawDescData
}

var file_task_executor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_task_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_task_executor_proto_goTypes = []any{
	(TaskExecutorResponse_Status)(0), // 0: core.task_executor.TaskExecutorResponse.Status
	(*TaskExecutorRequest)(nil),      // 1: core.task_executor.TaskExecutorRequest
	(*TaskExecutorResponse)(nil),     // 2: core.task_executor.TaskExecutorResponse
}
var file_task_executor_proto_depIdxs = []int32{
	0, // 0: core.task_executor.TaskExecutorResponse.status:type_name -> core.task_executor.TaskExecutorResponse.Status
	1, // 1: core.task_executor.TaskExecutorAdapter.SubmitTransaction:input_type -> core.task_executor.TaskExecutorRequest
	2, // 2: core.task_executor.TaskExecutorAdapter.SubmitTransaction:output_type -> core.task_executor.TaskExecutorResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_task_executor_proto_init() }
func file_task_executor_proto_init() {
	if File_task_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_executor_proto_rawDesc), len(file_task_executor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_executor_proto_goTypes,
		DependencyIndexes: file_task_executor_proto_depIdxs,
		EnumInfos:         file_task_executor_proto_enumTypes,
		MessageInfos:      file_task_executor_proto_msgTypes,
	}.Build()
	File_task_executor_proto = out.File
	file_task_executor_proto_goTypes = nil
	file_task_executor_proto_depIdxs = nil
}
