// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/anoideaopen/channel-transfer/test/integration/clihttp/models"
)

// MultiTransferByAdminReader is a Reader for the MultiTransferByAdmin structure.
type MultiTransferByAdminReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MultiTransferByAdminReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMultiTransferByAdminOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewMultiTransferByAdminInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewMultiTransferByAdminDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewMultiTransferByAdminOK creates a MultiTransferByAdminOK with default headers values
func NewMultiTransferByAdminOK() *MultiTransferByAdminOK {
	return &MultiTransferByAdminOK{}
}

/*
MultiTransferByAdminOK handles this case with default header values.

A successful response.
*/
type MultiTransferByAdminOK struct {
	Payload *models.ChannelTransferTransferStatusResponse
}

func (o *MultiTransferByAdminOK) Error() string {
	return fmt.Sprintf("[POST /v1/multi-transfer/admin][%d] multiTransferByAdminOK  %+v", 200, o.Payload)
}

func (o *MultiTransferByAdminOK) GetPayload() *models.ChannelTransferTransferStatusResponse {
	return o.Payload
}

func (o *MultiTransferByAdminOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelTransferTransferStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMultiTransferByAdminInternalServerError creates a MultiTransferByAdminInternalServerError with default headers values
func NewMultiTransferByAdminInternalServerError() *MultiTransferByAdminInternalServerError {
	return &MultiTransferByAdminInternalServerError{}
}

/*
MultiTransferByAdminInternalServerError handles this case with default header values.

Internal server error
*/
type MultiTransferByAdminInternalServerError struct {
	Payload *models.ChannelTransferErrorResponse
}

func (o *MultiTransferByAdminInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/multi-transfer/admin][%d] multiTransferByAdminInternalServerError  %+v", 500, o.Payload)
}

func (o *MultiTransferByAdminInternalServerError) GetPayload() *models.ChannelTransferErrorResponse {
	return o.Payload
}

func (o *MultiTransferByAdminInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelTransferErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMultiTransferByAdminDefault creates a MultiTransferByAdminDefault with default headers values
func NewMultiTransferByAdminDefault(code int) *MultiTransferByAdminDefault {
	return &MultiTransferByAdminDefault{
		_statusCode: code,
	}
}

/*
MultiTransferByAdminDefault handles this case with default header values.

An unexpected error response.
*/
type MultiTransferByAdminDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the multi transfer by admin default response
func (o *MultiTransferByAdminDefault) Code() int {
	return o._statusCode
}

func (o *MultiTransferByAdminDefault) Error() string {
	return fmt.Sprintf("[POST /v1/multi-transfer/admin][%d] multiTransferByAdmin default  %+v", o._statusCode, o.Payload)
}

func (o *MultiTransferByAdminDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *MultiTransferByAdminDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
