// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/anoideaopen/channel-transfer/test/integration/clihttp/models"
)

// MultiTransferByCustomerReader is a Reader for the MultiTransferByCustomer structure.
type MultiTransferByCustomerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MultiTransferByCustomerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMultiTransferByCustomerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewMultiTransferByCustomerInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewMultiTransferByCustomerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewMultiTransferByCustomerOK creates a MultiTransferByCustomerOK with default headers values
func NewMultiTransferByCustomerOK() *MultiTransferByCustomerOK {
	return &MultiTransferByCustomerOK{}
}

/*
MultiTransferByCustomerOK handles this case with default header values.

A successful response.
*/
type MultiTransferByCustomerOK struct {
	Payload *models.ChannelTransferTransferStatusResponse
}

func (o *MultiTransferByCustomerOK) Error() string {
	return fmt.Sprintf("[POST /v1/multi-transfer/customer][%d] multiTransferByCustomerOK  %+v", 200, o.Payload)
}

func (o *MultiTransferByCustomerOK) GetPayload() *models.ChannelTransferTransferStatusResponse {
	return o.Payload
}

func (o *MultiTransferByCustomerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelTransferTransferStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMultiTransferByCustomerInternalServerError creates a MultiTransferByCustomerInternalServerError with default headers values
func NewMultiTransferByCustomerInternalServerError() *MultiTransferByCustomerInternalServerError {
	return &MultiTransferByCustomerInternalServerError{}
}

/*
MultiTransferByCustomerInternalServerError handles this case with default header values.

Internal server error
*/
type MultiTransferByCustomerInternalServerError struct {
	Payload *models.ChannelTransferErrorResponse
}

func (o *MultiTransferByCustomerInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/multi-transfer/customer][%d] multiTransferByCustomerInternalServerError  %+v", 500, o.Payload)
}

func (o *MultiTransferByCustomerInternalServerError) GetPayload() *models.ChannelTransferErrorResponse {
	return o.Payload
}

func (o *MultiTransferByCustomerInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelTransferErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMultiTransferByCustomerDefault creates a MultiTransferByCustomerDefault with default headers values
func NewMultiTransferByCustomerDefault(code int) *MultiTransferByCustomerDefault {
	return &MultiTransferByCustomerDefault{
		_statusCode: code,
	}
}

/*
MultiTransferByCustomerDefault handles this case with default header values.

An unexpected error response.
*/
type MultiTransferByCustomerDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the multi transfer by customer default response
func (o *MultiTransferByCustomerDefault) Code() int {
	return o._statusCode
}

func (o *MultiTransferByCustomerDefault) Error() string {
	return fmt.Sprintf("[POST /v1/multi-transfer/customer][%d] multiTransferByCustomer default  %+v", o._statusCode, o.Payload)
}

func (o *MultiTransferByCustomerDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *MultiTransferByCustomerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
