// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/anoideaopen/channel-transfer/test/integration/clihttp/models"
)

// NewTransferByAdminParams creates a new TransferByAdminParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTransferByAdminParams() *TransferByAdminParams {
	return &TransferByAdminParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTransferByAdminParamsWithTimeout creates a new TransferByAdminParams object
// with the ability to set a timeout on a request.
func NewTransferByAdminParamsWithTimeout(timeout time.Duration) *TransferByAdminParams {
	return &TransferByAdminParams{
		timeout: timeout,
	}
}

// NewTransferByAdminParamsWithContext creates a new TransferByAdminParams object
// with the ability to set a context for a request.
func NewTransferByAdminParamsWithContext(ctx context.Context) *TransferByAdminParams {
	return &TransferByAdminParams{
		Context: ctx,
	}
}

// NewTransferByAdminParamsWithHTTPClient creates a new TransferByAdminParams object
// with the ability to set a custom HTTPClient for a request.
func NewTransferByAdminParamsWithHTTPClient(client *http.Client) *TransferByAdminParams {
	return &TransferByAdminParams{
		HTTPClient: client,
	}
}

/*
TransferByAdminParams contains all the parameters to send to the API endpoint

	for the transfer by admin operation.

	Typically these are written to a http.Request.
*/
type TransferByAdminParams struct {

	// Body.
	Body *models.ChannelTransferTransferBeginAdminRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the transfer by admin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TransferByAdminParams) WithDefaults() *TransferByAdminParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the transfer by admin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TransferByAdminParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the transfer by admin params
func (o *TransferByAdminParams) WithTimeout(timeout time.Duration) *TransferByAdminParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the transfer by admin params
func (o *TransferByAdminParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the transfer by admin params
func (o *TransferByAdminParams) WithContext(ctx context.Context) *TransferByAdminParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the transfer by admin params
func (o *TransferByAdminParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the transfer by admin params
func (o *TransferByAdminParams) WithHTTPClient(client *http.Client) *TransferByAdminParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the transfer by admin params
func (o *TransferByAdminParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the transfer by admin params
func (o *TransferByAdminParams) WithBody(body *models.ChannelTransferTransferBeginAdminRequest) *TransferByAdminParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the transfer by admin params
func (o *TransferByAdminParams) SetBody(body *models.ChannelTransferTransferBeginAdminRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TransferByAdminParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
