// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTransferStatusParams creates a new TransferStatusParams object
// with the default values initialized.
func NewTransferStatusParams() *TransferStatusParams {
	var ()
	return &TransferStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTransferStatusParamsWithTimeout creates a new TransferStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTransferStatusParamsWithTimeout(timeout time.Duration) *TransferStatusParams {
	var ()
	return &TransferStatusParams{

		timeout: timeout,
	}
}

// NewTransferStatusParamsWithContext creates a new TransferStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewTransferStatusParamsWithContext(ctx context.Context) *TransferStatusParams {
	var ()
	return &TransferStatusParams{

		Context: ctx,
	}
}

// NewTransferStatusParamsWithHTTPClient creates a new TransferStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTransferStatusParamsWithHTTPClient(client *http.Client) *TransferStatusParams {
	var ()
	return &TransferStatusParams{
		HTTPClient: client,
	}
}

/*
TransferStatusParams contains all the parameters to send to the API endpoint
for the transfer status operation typically these are written to a http.Request
*/
type TransferStatusParams struct {

	/*IDTransfer
	  transfer ID

	*/
	IDTransfer string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the transfer status params
func (o *TransferStatusParams) WithTimeout(timeout time.Duration) *TransferStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the transfer status params
func (o *TransferStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the transfer status params
func (o *TransferStatusParams) WithContext(ctx context.Context) *TransferStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the transfer status params
func (o *TransferStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the transfer status params
func (o *TransferStatusParams) WithHTTPClient(client *http.Client) *TransferStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the transfer status params
func (o *TransferStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIDTransfer adds the iDTransfer to the transfer status params
func (o *TransferStatusParams) WithIDTransfer(iDTransfer string) *TransferStatusParams {
	o.SetIDTransfer(iDTransfer)
	return o
}

// SetIDTransfer adds the idTransfer to the transfer status params
func (o *TransferStatusParams) SetIDTransfer(iDTransfer string) {
	o.IDTransfer = iDTransfer
}

// WriteToRequest writes these params to a swagger request
func (o *TransferStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param idTransfer
	if err := r.SetPathParam("idTransfer", o.IDTransfer); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
