// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/anoideaopen/channel-transfer/test/integration/clihttp/models"
)

// TransferByAdminReader is a Reader for the TransferByAdmin structure.
type TransferByAdminReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TransferByAdminReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTransferByAdminOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewTransferByAdminInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewTransferByAdminDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewTransferByAdminOK creates a TransferByAdminOK with default headers values
func NewTransferByAdminOK() *TransferByAdminOK {
	return &TransferByAdminOK{}
}

/*
TransferByAdminOK describes a response with status code 200, with default header values.

A successful response.
*/
type TransferByAdminOK struct {
	Payload *models.ChannelTransferTransferStatusResponse
}

// IsSuccess returns true when this transfer by admin o k response has a 2xx status code
func (o *TransferByAdminOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this transfer by admin o k response has a 3xx status code
func (o *TransferByAdminOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this transfer by admin o k response has a 4xx status code
func (o *TransferByAdminOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this transfer by admin o k response has a 5xx status code
func (o *TransferByAdminOK) IsServerError() bool {
	return false
}

// IsCode returns true when this transfer by admin o k response a status code equal to that given
func (o *TransferByAdminOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the transfer by admin o k response
func (o *TransferByAdminOK) Code() int {
	return 200
}

func (o *TransferByAdminOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/transfer/admin][%d] transferByAdminOK %s", 200, payload)
}

func (o *TransferByAdminOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/transfer/admin][%d] transferByAdminOK %s", 200, payload)
}

func (o *TransferByAdminOK) GetPayload() *models.ChannelTransferTransferStatusResponse {
	return o.Payload
}

func (o *TransferByAdminOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelTransferTransferStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTransferByAdminInternalServerError creates a TransferByAdminInternalServerError with default headers values
func NewTransferByAdminInternalServerError() *TransferByAdminInternalServerError {
	return &TransferByAdminInternalServerError{}
}

/*
TransferByAdminInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type TransferByAdminInternalServerError struct {
	Payload *models.ChannelTransferErrorResponse
}

// IsSuccess returns true when this transfer by admin internal server error response has a 2xx status code
func (o *TransferByAdminInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this transfer by admin internal server error response has a 3xx status code
func (o *TransferByAdminInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this transfer by admin internal server error response has a 4xx status code
func (o *TransferByAdminInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this transfer by admin internal server error response has a 5xx status code
func (o *TransferByAdminInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this transfer by admin internal server error response a status code equal to that given
func (o *TransferByAdminInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the transfer by admin internal server error response
func (o *TransferByAdminInternalServerError) Code() int {
	return 500
}

func (o *TransferByAdminInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/transfer/admin][%d] transferByAdminInternalServerError %s", 500, payload)
}

func (o *TransferByAdminInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/transfer/admin][%d] transferByAdminInternalServerError %s", 500, payload)
}

func (o *TransferByAdminInternalServerError) GetPayload() *models.ChannelTransferErrorResponse {
	return o.Payload
}

func (o *TransferByAdminInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelTransferErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTransferByAdminDefault creates a TransferByAdminDefault with default headers values
func NewTransferByAdminDefault(code int) *TransferByAdminDefault {
	return &TransferByAdminDefault{
		_statusCode: code,
	}
}

/*
TransferByAdminDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type TransferByAdminDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this transfer by admin default response has a 2xx status code
func (o *TransferByAdminDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this transfer by admin default response has a 3xx status code
func (o *TransferByAdminDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this transfer by admin default response has a 4xx status code
func (o *TransferByAdminDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this transfer by admin default response has a 5xx status code
func (o *TransferByAdminDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this transfer by admin default response a status code equal to that given
func (o *TransferByAdminDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the transfer by admin default response
func (o *TransferByAdminDefault) Code() int {
	return o._statusCode
}

func (o *TransferByAdminDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/transfer/admin][%d] transferByAdmin default %s", o._statusCode, payload)
}

func (o *TransferByAdminDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/transfer/admin][%d] transferByAdmin default %s", o._statusCode, payload)
}

func (o *TransferByAdminDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *TransferByAdminDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
