// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/anoideaopen/channel-transfer/test/integration/clihttp/models"
)

// TransferByCustomerReader is a Reader for the TransferByCustomer structure.
type TransferByCustomerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TransferByCustomerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTransferByCustomerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewTransferByCustomerInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewTransferByCustomerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewTransferByCustomerOK creates a TransferByCustomerOK with default headers values
func NewTransferByCustomerOK() *TransferByCustomerOK {
	return &TransferByCustomerOK{}
}

/*
TransferByCustomerOK describes a response with status code 200, with default header values.

A successful response.
*/
type TransferByCustomerOK struct {
	Payload *models.ChannelTransferTransferStatusResponse
}

// IsSuccess returns true when this transfer by customer o k response has a 2xx status code
func (o *TransferByCustomerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this transfer by customer o k response has a 3xx status code
func (o *TransferByCustomerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this transfer by customer o k response has a 4xx status code
func (o *TransferByCustomerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this transfer by customer o k response has a 5xx status code
func (o *TransferByCustomerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this transfer by customer o k response a status code equal to that given
func (o *TransferByCustomerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the transfer by customer o k response
func (o *TransferByCustomerOK) Code() int {
	return 200
}

func (o *TransferByCustomerOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/transfer/customer][%d] transferByCustomerOK %s", 200, payload)
}

func (o *TransferByCustomerOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/transfer/customer][%d] transferByCustomerOK %s", 200, payload)
}

func (o *TransferByCustomerOK) GetPayload() *models.ChannelTransferTransferStatusResponse {
	return o.Payload
}

func (o *TransferByCustomerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelTransferTransferStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTransferByCustomerInternalServerError creates a TransferByCustomerInternalServerError with default headers values
func NewTransferByCustomerInternalServerError() *TransferByCustomerInternalServerError {
	return &TransferByCustomerInternalServerError{}
}

/*
TransferByCustomerInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type TransferByCustomerInternalServerError struct {
	Payload *models.ChannelTransferErrorResponse
}

// IsSuccess returns true when this transfer by customer internal server error response has a 2xx status code
func (o *TransferByCustomerInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this transfer by customer internal server error response has a 3xx status code
func (o *TransferByCustomerInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this transfer by customer internal server error response has a 4xx status code
func (o *TransferByCustomerInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this transfer by customer internal server error response has a 5xx status code
func (o *TransferByCustomerInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this transfer by customer internal server error response a status code equal to that given
func (o *TransferByCustomerInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the transfer by customer internal server error response
func (o *TransferByCustomerInternalServerError) Code() int {
	return 500
}

func (o *TransferByCustomerInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/transfer/customer][%d] transferByCustomerInternalServerError %s", 500, payload)
}

func (o *TransferByCustomerInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/transfer/customer][%d] transferByCustomerInternalServerError %s", 500, payload)
}

func (o *TransferByCustomerInternalServerError) GetPayload() *models.ChannelTransferErrorResponse {
	return o.Payload
}

func (o *TransferByCustomerInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelTransferErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTransferByCustomerDefault creates a TransferByCustomerDefault with default headers values
func NewTransferByCustomerDefault(code int) *TransferByCustomerDefault {
	return &TransferByCustomerDefault{
		_statusCode: code,
	}
}

/*
TransferByCustomerDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type TransferByCustomerDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this transfer by customer default response has a 2xx status code
func (o *TransferByCustomerDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this transfer by customer default response has a 3xx status code
func (o *TransferByCustomerDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this transfer by customer default response has a 4xx status code
func (o *TransferByCustomerDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this transfer by customer default response has a 5xx status code
func (o *TransferByCustomerDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this transfer by customer default response a status code equal to that given
func (o *TransferByCustomerDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the transfer by customer default response
func (o *TransferByCustomerDefault) Code() int {
	return o._statusCode
}

func (o *TransferByCustomerDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/transfer/customer][%d] transferByCustomer default %s", o._statusCode, payload)
}

func (o *TransferByCustomerDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/transfer/customer][%d] transferByCustomer default %s", o._statusCode, payload)
}

func (o *TransferByCustomerDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *TransferByCustomerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
