logLevel: debug
logType: console
profilePath: dev-data/sandbox/connection.yaml
userName: User1
useSmartBFT: true

listenAPI:
  accessToken: ea135929105c4f29a0f5117d2980926f
  addressHTTP: localhost:5080
  addressGRPC: localhost:5081

service:
  address: :3001

options:
  batchTxPreimagePrefix: batchTransactions
  collectorsBufSize: 1 # buffer size of blockData
  executeTimeout: 0s # timeout of invoke HLF SDK method
  retryExecuteAttempts: 3 # number of attempts querying the HLF
  retryExecuteMaxDelay: 2s # delay between attempts querying the HLF
  retryExecuteDelay: 500ms # delay between attempts querying the HLF
  ttl: 10800s # time to live of transfer
  transfersInHandleOnChannel: 50 # the number of transfers currently being processed in the channel
  newestRequestStreamBufferSize: 50 # size of the request buffer of creating transfers

channels:
  - fiat
  - cc

cryptoSrc: local

redisStorage:
  addr:
    - localhost:6379
  password: test
  dbPrefix: transfer
  afterTransferTTL: 3600s

promMetrics:
  prefix: transfer
