name: "Go Verify Build"

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  check-cyrillic-comments:
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v7
      - name: check cyrillic comments
        run: |
          ! LC_ALL=en_US.UTF-8 grep --exclude-dir=.git --exclude-dir=.github --exclude-dir=.idea -I -r --color -n -E "[А-Яа-яЁё]+" .

  validate-go:
    needs:
      - check-cyrillic-comments
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v7

      - name: setup go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: check go.mod
        run: |
          go mod tidy
          git diff --exit-code go.mod

      - name: go fmt
        run: |
          go fmt ./...
          git diff --exit-code

  golangci-lint:
    needs:
      - validate-go
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v7
      - name: setup go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.9.0
          skip-cache: true
          problem-matchers: true

  go-unit-test:
    needs:
      - golangci-lint
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: unit test
        run: |
          go test -count 1 ./...

  go-test-coverage:
    needs:
      - golangci-lint
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: generate test coverage
        run: |
          go test ./... -coverprofile=./coverage.out

      # https://github.com/vladopajic/go-test-coverage
      - uses: vladopajic/go-test-coverage@v2.18.9
        with:
          config: ./.testcoverage.yml
          profile: coverage.out
          local-prefix: github.com/${{ github.repository }}

  go-test-integration:
    needs:
      - golangci-lint
    strategy:
      fail-fast: false
      matrix:
        INTEGRATION_TEST_SUITE: [ "grpc","http","chaos","task-executor" ]
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: redis
        run: docker pull redis:7.2.4
      - name: fabric-ccenv
        run: docker pull hyperledger/fabric-ccenv:latest
      - name: fabric-baseos
        run: docker pull hyperledger/fabric-baseos:latest
      - name: integration test
        working-directory: ./test/integration
        run: |
          go run github.com/onsi/ginkgo/v2/ginkgo --keep-going --poll-progress-after 60s --timeout 24h ${{matrix.INTEGRATION_TEST_SUITE}}
