name: Release

on:
  workflow_dispatch: # workflow_dispatch must be enabled in main branch to support release action on older release branches
  push:
    tags:
      - 'v*'

env:
  UBUNTU_VER: 24.04
  APP_VER: ${{ github.ref_name }}

permissions:
  contents: read

jobs:
  # build native images using a different runner for each architecture (faster and more reliable than using qemu to build multi-architecture images on ubuntu-24.04)
  build-and-push-native-docker-images:
    name: Build and Push native images
    runs-on: ${{ matrix.runner }}

    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04 # creates linux-amd64 images
          - ubuntu-24.04-arm # creates linux-arm64 images

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set GO_VER from go.mod
        run: echo "GO_VER=$(awk '/^go /{print $2}' go.mod)" >> "$GITHUB_ENV"

      - name: Login to the docker.com Container Registry
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: scientificideas/channel-transfer

      - name: Build and push channel-transfer Image
        id: build-and-push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            APP_VER=${{ env.APP_VER }}
            UBUNTU_VER=${{ env.UBUNTU_VER }}
            GO_VER=${{ env.GO_VER }}
          outputs: type=image,"name=scientificideas/channel-transfer",push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests/channel-transfer
          digest="${{ steps.build-and-push.outputs.digest }}"
          touch "${{ runner.temp }}/digests/channel-transfer/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v7
        with:
          name: digests-channel-transfer-${{ matrix.runner }}
          path: ${{ runner.temp }}/digests/channel-transfer/*
          if-no-files-found: error
          retention-days: 1

  # This job merges the architecture-specific digests for the images created above
  # and creates a multi-architecture image manifest with user-friendly tags
  merge-and-push-multi-arch-image:
    name: Merge and Push multi-arch image
    runs-on: ubuntu-24.04
    needs:
      - build-and-push-native-docker-images

    permissions:
      contents: read
      packages: write

    steps:
      - name: Download digests
        uses: actions/download-artifact@v8
        with:
          path: ${{ runner.temp }}/digests/channel-transfer
          pattern: digests-channel-transfer-*
          merge-multiple: true

      - name: Login to the docker.com Container Registry
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: scientificideas/channel-transfer
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}

      - name: Create manifest list and push # combines the downloaded amd64 and arm64 digests and pushes multi-architecture manifest with the tags specified above
        working-directory: ${{ runner.temp }}/digests/channel-transfer
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf 'scientificideas/channel-transfer@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect scientificideas/channel-transfer:${{ steps.meta.outputs.version }}
