name: "Security vulnerability scan"

on:
  workflow_dispatch:
  schedule:
    - cron: "50 1 * * *"
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
  actions: read
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # to fetch code (actions/checkout)
  contents: read

jobs:
  scan-scheduled:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.2.2"
    with:
      scan-args: |-
        --config ./osv-scanner-config.toml
        --recursive
        ./

  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.2.2"
    with:
      scan-args: |-
        --config ./osv-scanner-config.toml
        --recursive
        ./
