name: "Security vulnerability scan"

on:
  workflow_dispatch:
  schedule:
    - cron: "50 1 * * *"

env:
  GO_VER: 1.21.9

permissions:
  contents: read

jobs:
  # https://github.com/golang/govulncheck-action
  govulncheck:
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ env.GO_VER }}

  # https://github.com/sonatype-nexus-community/nancy-github-action
  sonatype:
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VER }}
      - run: go list -json -deps ./... > go.list
      - uses: sonatype-nexus-community/nancy-github-action@v1.0.3